services:
  aurora_front:
    build:
      context: .
    working_dir: /app # <-- run commands in /app
    ports:
      - "3000:3000"
    env_file:
      - aurora-front/.env.local
    volumes:
      - ./aurora-front:/app # <-- mount the app folder, not "."
      - node_deps:/app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true # required for Windows FS
      - WATCHPACK_POLLING=true
      - WATCHPACK_POLLING_INTERVAL=500
      - NEXT_DISABLE_TURBOPACK=1
    command: sh -c "npm run dev --webpack"
volumes:
  node_deps:
