services:
  aurora-admin:
    build:
      context: ../aurora-admin
      dockerfile: Dockerfile.admin
    working_dir: /app
    ports:
      - "3002:3000"
    env_file:
      - ../aurora-admin/.env.local
    volumes:
      - ../aurora-admin:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - WATCHPACK_POLLING_INTERVAL=500
      - NEXT_DISABLE_TURBOPACK=1
    command: sh -c "npm run dev --webpack"
  aurora-redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
  aurora-front:
    build:
      context: ../aurora-front
      dockerfile: Dockerfile.front
    working_dir: /app
    ports:
      - "3000:3000"
    env_file:
      - ../aurora-front/.env.local
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - ../aurora-front:/app
    depends_on:
      aurora-redis:
        condition: service_started
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true # required for Windows FS
      - WATCHPACK_POLLING=true
      - WATCHPACK_POLLING_INTERVAL=500
      - NEXT_DISABLE_TURBOPACK=1
      - NODE_OPTIONS=--dns-result-order=ipv4first
    command: sh -c "npm run dev --webpack"
  aurora-front-prod:
    build:
      context: ../aurora-front
      dockerfile: Dockerfile.prod
    ports:
      - "3001:3000"
    env_file:
      - ../aurora-front/.env.local
    environment:
      - NODE_ENV=production
    depends_on:
      aurora-redis:
        condition: service_started
  aurora-back:
    build:
      context: ../aurora-back
      dockerfile: Dockerfile.back
    depends_on:
      aurora-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://aurora-db:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    working_dir: /app
    ports:
      - "${BACKEND_PORT}:8080"
    env_file:
      - ../aurora-back/.env
    volumes:
      - ../aurora-back/src:/app/src
      - ../aurora-back/secrets.properties:/app/secrets.properties
      - /app/node_modules
    command: ./mvnw spring-boot:run
  aurora-db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d # optional init scripts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      retries: 5
  # aurora-nginx:
  #   image: nginx:1.26-alpine
  #   container_name: aurora-nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./nginx/conf.d:/etc/nginx/conf.d:ro
  #   depends_on:
  #     - aurora-front
  #     - aurora-back
  #     - aurora-db
  #     - aurora-admin
  #   networks:
  #     - aurora-net
volumes:
  # node_deps:
  pgdata:
  redis-data:
# networks:
#   aurora-net:
#     driver: bridge
