services:
  aurora-front:
    build:
      context: ../aurora-front
      dockerfile: Dockerfile.front
    working_dir: /app # <-- run commands in /app
    ports:
      - "3000:3000"
    env_file:
      - ../aurora-front/.env.local
    dns:
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - ../aurora-front:/app # <-- mount the app folder, not "."
      - node_deps:/app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true # required for Windows FS
      - WATCHPACK_POLLING=true
      - WATCHPACK_POLLING_INTERVAL=500
      - NEXT_DISABLE_TURBOPACK=1
    command: sh -c "npm run dev --webpack"
  aurora-back:
    build:
      context: ../aurora-back
      dockerfile: Dockerfile.back
    working_dir: /app
    ports:
      - "8080:8080"
    env_file:
      - ../aurora-back/.env
    volumes:
      - ./src:/app/src
    command: ./mvnw spring-boot:run
volumes:
  node_deps:
